import { StyleSheet } from '@react-pdf/renderer'
import { fontFamilies } from './fonts'
import type { ReportFormat } from './page-sizes'

export const colors = {
  chambray: '#39419a',
  chambrayDeep: '#1e3260',
  sanmarino: '#406eb5',
  casablanca: '#f6b03f',
  positive: '#406eb5',
  neutral: '#a8b8e8',
  negative: '#d94f4f',
  slate600: '#475569',
  slate500: '#64748b',
  slate200: '#e2e8f0',
  white: '#ffffff',
  pageBg: '#f8fafc',
  coverGradientStart: '#1e3260',
  coverGradientEnd: '#39419a',
} as const

const letterStyles = StyleSheet.create({
  page: {
    paddingTop: 40,
    paddingBottom: 52,
    paddingHorizontal: 48,
    fontFamily: fontFamilies.body,
    fontSize: 12,
    color: colors.chambray,
    backgroundColor: colors.pageBg,
  },
  coverPage: {
    paddingTop: 48,
    paddingBottom: 40,
    paddingHorizontal: 48,
    backgroundColor: colors.coverGradientEnd,
    color: colors.white,
    fontFamily: fontFamilies.body,
    flex: 1,
    justifyContent: 'space-between',
  },
  coverLogoWell: {
    width: 128,
    height: 128,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.14)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 32,
  },
  coverLogoImage: {
    width: 100,
    height: 100,
    objectFit: 'contain',
  },
  coverLogoMonogram: {
    fontSize: 40,
    fontFamily: fontFamilies.display,
    color: colors.casablanca,
  },
  coverEyebrow: {
    fontSize: 10,
    letterSpacing: 3,
    textTransform: 'uppercase',
    color: colors.casablanca,
    marginBottom: 12,
    fontFamily: fontFamilies.body,
    fontWeight: 600,
  },
  coverTitle: {
    fontSize: 44,
    fontFamily: fontFamilies.display,
    marginBottom: 10,
    color: colors.white,
  },
  coverSubtitle: {
    fontSize: 18,
    color: '#c8d4ef',
    marginBottom: 20,
    fontFamily: fontFamilies.body,
    fontWeight: 600,
  },
  coverAccentLine: {
    width: 72,
    height: 4,
    backgroundColor: colors.casablanca,
    marginBottom: 20,
    borderRadius: 2,
  },
  coverMeta: {
    fontSize: 11,
    color: '#a8b8e8',
    lineHeight: 1.8,
    fontFamily: fontFamilies.body,
  },
  coverFooter: {
    fontSize: 9,
    color: 'rgba(255,255,255,0.6)',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    fontFamily: fontFamilies.body,
    fontWeight: 600,
  },
  masthead: {
    marginHorizontal: -48,
    marginTop: -40,
    marginBottom: 24,
    paddingVertical: 20,
    paddingHorizontal: 48,
    backgroundColor: colors.chambray,
  },
  mastheadEyebrow: {
    fontSize: 9,
    letterSpacing: 2.5,
    textTransform: 'uppercase',
    color: colors.casablanca,
    marginBottom: 4,
    fontFamily: fontFamilies.body,
    fontWeight: 600,
  },
  mastheadTitle: {
    fontSize: 26,
    fontFamily: fontFamilies.display,
    color: colors.white,
  },
  interiorHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.slate200,
  },
  interiorHeaderOrg: {
    fontSize: 11,
    fontFamily: fontFamilies.body,
    fontWeight: 600,
    color: colors.chambray,
  },
  interiorHeaderSection: {
    fontSize: 10,
    color: colors.slate500,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
  },
  sectionTitle: {
    fontSize: 22,
    fontFamily: fontFamilies.display,
    color: colors.chambray,
    marginBottom: 4,
  },
  sectionDesc: {
    fontSize: 12,
    color: colors.slate500,
    marginBottom: 14,
    lineHeight: 1.5,
  },
  chartCard: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.slate200,
    marginBottom: 16,
  },
  chartCardTitle: {
    fontSize: 14,
    fontFamily: fontFamilies.body,
    fontWeight: 700,
    color: colors.chambray,
    marginBottom: 4,
  },
  chartCardSubtitle: {
    fontSize: 11,
    color: colors.slate500,
    marginBottom: 12,
  },
  callout: {
    backgroundColor: '#fff8eb',
    borderLeftWidth: 4,
    borderLeftColor: colors.casablanca,
    borderRadius: 8,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 20,
  },
  calloutHeadline: {
    fontSize: 14,
    fontFamily: fontFamilies.body,
    fontWeight: 700,
    color: colors.chambray,
    marginBottom: 4,
  },
  calloutDetail: {
    fontSize: 11,
    color: colors.slate600,
    lineHeight: 1.5,
  },
  heroKpiStrip: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 16,
  },
  heroKpiItem: {
    flex: 1,
    backgroundColor: colors.white,
    borderRadius: 10,
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: colors.slate200,
    alignItems: 'center',
  },
  heroKpiLabel: {
    fontSize: 9,
    color: colors.slate500,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 6,
    textAlign: 'center',
  },
  heroKpiValue: {
    fontSize: 28,
    fontFamily: fontFamilies.body,
    fontWeight: 700,
    color: colors.chambray,
    textAlign: 'center',
  },
  heroKpiSub: {
    fontSize: 9,
    color: colors.slate500,
    marginTop: 4,
    textAlign: 'center',
  },
  heroKpiDelta: {
    fontSize: 9,
    fontFamily: fontFamilies.body,
    fontWeight: 600,
    marginTop: 4,
    textAlign: 'center',
  },
  legendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  legendSwatch: {
    width: 10,
    height: 10,
    borderRadius: 2,
    marginRight: 8,
  },
  legendLabel: {
    fontSize: 11,
    color: colors.chambray,
    flex: 1,
  },
  legendValue: {
    fontSize: 11,
    fontFamily: fontFamilies.body,
    fontWeight: 600,
    color: colors.slate600,
  },
  footer: {
    position: 'absolute',
    bottom: 22,
    left: 48,
    right: 48,
    flexDirection: 'row',
    justifyContent: 'space-between',
    fontSize: 9,
    color: colors.slate500,
    borderTopWidth: 1,
    borderTopColor: colors.slate200,
    paddingTop: 8,
    fontFamily: fontFamilies.body,
  },
  kpiGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  kpiCard: {
    width: '48%',
    backgroundColor: colors.white,
    borderRadius: 10,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.slate200,
  },
  kpiLabel: {
    fontSize: 9,
    color: colors.slate500,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 4,
  },
  kpiValue: {
    fontSize: 24,
    fontFamily: fontFamilies.body,
    fontWeight: 700,
    color: colors.chambray,
  },
  kpiSub: {
    fontSize: 10,
    color: colors.slate500,
    marginTop: 2,
  },
  compareChip: {
    fontSize: 10,
    fontFamily: fontFamilies.body,
    fontWeight: 600,
    color: colors.sanmarino,
    backgroundColor: '#eef3fb',
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 12,
    alignSelf: 'flex-start',
    marginBottom: 12,
  },
  tableHeader: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: colors.slate200,
    paddingBottom: 8,
    marginBottom: 6,
    backgroundColor: colors.white,
  },
  tableRow: {
    flexDirection: 'row',
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  cell: {
    fontSize: 11,
    color: colors.slate600,
  },
  cellBold: {
    fontSize: 11,
    fontFamily: fontFamilies.body,
    fontWeight: 700,
    color: colors.chambray,
  },
})

const deckStyles = StyleSheet.create({
  page: {
    paddingTop: 64,
    paddingBottom: 72,
    paddingHorizontal: 96,
    fontFamily: fontFamilies.body,
    fontSize: 20,
    color: colors.chambray,
    backgroundColor: colors.pageBg,
  },
  coverPage: {
    paddingTop: 80,
    paddingBottom: 64,
    paddingHorizontal: 120,
    backgroundColor: colors.coverGradientEnd,
    color: colors.white,
    fontFamily: fontFamilies.body,
    flex: 1,
    justifyContent: 'space-between',
  },
  coverLogoWell: {
    width: 240,
    height: 240,
    borderRadius: 32,
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.28)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 52,
  },
  coverLogoImage: {
    width: 200,
    height: 200,
    objectFit: 'contain',
  },
  coverLogoMonogram: {
    fontSize: 80,
    fontFamily: fontFamilies.display,
    color: colors.casablanca,
  },
  coverEyebrow: {
    fontSize: 18,
    letterSpacing: 4,
    textTransform: 'uppercase',
    color: colors.casablanca,
    marginBottom: 24,
    fontFamily: fontFamilies.body,
    fontWeight: 600,
  },
  coverTitle: {
    fontSize: 72,
    fontFamily: fontFamilies.display,
    marginBottom: 16,
    color: colors.white,
  },
  coverSubtitle: {
    fontSize: 36,
    color: '#c8d4ef',
    marginBottom: 32,
    fontFamily: fontFamilies.body,
    fontWeight: 600,
  },
  coverAccentLine: {
    width: 140,
    height: 6,
    backgroundColor: colors.casablanca,
    marginBottom: 32,
    borderRadius: 3,
  },
  coverMeta: {
    fontSize: 22,
    color: '#a8b8e8',
    lineHeight: 1.7,
    fontFamily: fontFamilies.body,
  },
  coverFooter: {
    fontSize: 16,
    color: 'rgba(255,255,255,0.55)',
    letterSpacing: 2,
    textTransform: 'uppercase',
    fontFamily: fontFamilies.body,
    fontWeight: 600,
  },
  masthead: {
    marginHorizontal: -96,
    marginTop: -64,
    marginBottom: 40,
    paddingVertical: 36,
    paddingHorizontal: 96,
    backgroundColor: colors.chambray,
  },
  mastheadEyebrow: {
    fontSize: 16,
    letterSpacing: 3,
    textTransform: 'uppercase',
    color: colors.casablanca,
    marginBottom: 8,
    fontFamily: fontFamilies.body,
    fontWeight: 600,
  },
  mastheadTitle: {
    fontSize: 48,
    fontFamily: fontFamilies.display,
    color: colors.white,
  },
  interiorHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 28,
    paddingBottom: 12,
    borderBottomWidth: 2,
    borderBottomColor: colors.slate200,
  },
  interiorHeaderOrg: {
    fontSize: 20,
    fontFamily: fontFamilies.body,
    fontWeight: 600,
    color: colors.chambray,
  },
  interiorHeaderSection: {
    fontSize: 16,
    color: colors.slate500,
    textTransform: 'uppercase',
    letterSpacing: 1.5,
  },
  sectionTitle: {
    fontSize: 40,
    fontFamily: fontFamilies.display,
    color: colors.chambray,
    marginBottom: 8,
  },
  sectionDesc: {
    fontSize: 20,
    color: colors.slate500,
    marginBottom: 24,
    lineHeight: 1.5,
  },
  chartCard: {
    backgroundColor: colors.white,
    borderRadius: 20,
    padding: 28,
    borderWidth: 1,
    borderColor: colors.slate200,
    marginBottom: 24,
  },
  chartCardTitle: {
    fontSize: 26,
    fontFamily: fontFamilies.body,
    fontWeight: 700,
    color: colors.chambray,
    marginBottom: 6,
  },
  chartCardSubtitle: {
    fontSize: 18,
    color: colors.slate500,
    marginBottom: 20,
  },
  callout: {
    backgroundColor: '#fff8eb',
    borderLeftWidth: 6,
    borderLeftColor: colors.casablanca,
    borderRadius: 12,
    paddingVertical: 24,
    paddingHorizontal: 28,
    marginBottom: 32,
  },
  calloutHeadline: {
    fontSize: 28,
    fontFamily: fontFamilies.body,
    fontWeight: 700,
    color: colors.chambray,
    marginBottom: 8,
  },
  calloutDetail: {
    fontSize: 20,
    color: colors.slate600,
    lineHeight: 1.5,
  },
  heroKpiStrip: {
    flexDirection: 'row',
    gap: 20,
    marginBottom: 28,
  },
  heroKpiItem: {
    flex: 1,
    backgroundColor: colors.white,
    borderRadius: 16,
    paddingVertical: 24,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: colors.slate200,
    alignItems: 'center',
  },
  heroKpiLabel: {
    fontSize: 14,
    color: colors.slate500,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    marginBottom: 10,
    textAlign: 'center',
  },
  heroKpiValue: {
    fontSize: 52,
    fontFamily: fontFamilies.body,
    fontWeight: 700,
    color: colors.chambray,
    textAlign: 'center',
  },
  heroKpiSub: {
    fontSize: 14,
    color: colors.slate500,
    marginTop: 6,
    textAlign: 'center',
  },
  heroKpiDelta: {
    fontSize: 14,
    fontFamily: fontFamilies.body,
    fontWeight: 600,
    marginTop: 6,
    textAlign: 'center',
  },
  legendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  legendSwatch: {
    width: 16,
    height: 16,
    borderRadius: 4,
    marginRight: 12,
  },
  legendLabel: {
    fontSize: 18,
    color: colors.chambray,
    flex: 1,
  },
  legendValue: {
    fontSize: 18,
    fontFamily: fontFamilies.body,
    fontWeight: 600,
    color: colors.slate600,
  },
  footer: {
    position: 'absolute',
    bottom: 36,
    left: 96,
    right: 96,
    flexDirection: 'row',
    justifyContent: 'space-between',
    fontSize: 14,
    color: colors.slate500,
    borderTopWidth: 1,
    borderTopColor: colors.slate200,
    paddingTop: 12,
    fontFamily: fontFamilies.body,
  },
  kpiGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 20,
  },
  kpiCard: {
    width: '48%',
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 24,
    borderWidth: 1,
    borderColor: colors.slate200,
  },
  kpiLabel: {
    fontSize: 14,
    color: colors.slate500,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    marginBottom: 8,
  },
  kpiValue: {
    fontSize: 44,
    fontFamily: fontFamilies.body,
    fontWeight: 700,
    color: colors.chambray,
  },
  kpiSub: {
    fontSize: 16,
    color: colors.slate500,
    marginTop: 6,
  },
  compareChip: {
    fontSize: 18,
    fontFamily: fontFamilies.body,
    fontWeight: 600,
    color: colors.sanmarino,
    backgroundColor: '#eef3fb',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    alignSelf: 'flex-start',
    marginBottom: 20,
  },
  tableHeader: {
    flexDirection: 'row',
    borderBottomWidth: 2,
    borderBottomColor: colors.slate200,
    paddingBottom: 12,
    marginBottom: 10,
    backgroundColor: colors.white,
  },
  tableRow: {
    flexDirection: 'row',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  cell: {
    fontSize: 18,
    color: colors.slate600,
  },
  cellBold: {
    fontSize: 18,
    fontFamily: fontFamilies.body,
    fontWeight: 700,
    color: colors.chambray,
  },
})

export type ReportTheme = typeof letterStyles

export const letterTheme = letterStyles
export const deckTheme = deckStyles

/** @deprecated Use letterTheme or getReportTheme() */
export const theme = letterTheme

export function getReportTheme(format: ReportFormat): ReportTheme {
  return format === 'deck' ? deckTheme : letterTheme
}

export function pageBleed(format: ReportFormat): number {
  return format === 'deck' ? 96 : 48
}
